/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sasi-kathimanda' at '21/2/16 1:00 AM' with Gradle 2.8
 *
 * @author sasi-kathimanda, @date 21/2/16 1:00 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
